### ISSUE TITLE
This work is very good. When will the code be open?

### ISSUE THREAD

**Issue by xmu-xiaoma666** [sushizixin/CLIP4IDC#1]

**Comment by sushizixin** [comment]
We are still improving the results and we plan to release the code this summer.

**Comment by jinga-lala** [comment]
Hi @sushizixin, I wanted to check-in if the code of your method along with the implemented baselines can be released sooner?

Thanks

**Comment by sushizixin** [comment]
Hi @jinga-lala, the results of the code and the model have been improved. We will release them in several days.
