### ISSUE TITLE
Visualization of the vision encoder's output

### ISSUE THREAD

**Issue by pooyanrg** [sushizixin/CLIP4IDC#2]
Congratulations for your impressive work! I was trying to reproduce the results reported in the paper, but I could not find the piece of code for generating heat maps in Fig. 3 to Fig. 4.

Could you please help me both understand and reproduce the results in the appendix of your paper? My specific questions are:

1. How do you produce these heat maps?

2. It seems that in case of no change in the image pair, the encoder still highlights some regions. Did you have any chance to find out why?

Thanks!

**Comment by Adasunnylily** [comment]
hi， were you able to reproduce the acc as reported in the paper?

**Comment by pooyanrg** [comment]
Hi @Adasunnylily 

Yes, I have reproduced all the results reported in the paper using the bash scripts in the repo.
